version: '3.7'
services:
  maksut-nginx-local:
    image: nginx
    container_name: maksut-nginx-local
    networks:
      maksut-local-network:
    ports:
      - "9030:9030"
      - "19030:19030"
    volumes:
      - "./nginx:/etc/nginx"
  maksut-e2e-db-local:
    image: postgres:15-alpine
    container_name: maksut-e2e-db-local
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: maksut
    networks:
      maksut-local-e2e-network:
    ports:
      - "15432:15432"
    command: -p 15432
  maksut-db-local:
    image: postgres:15-alpine
    container_name: maksut-db-local
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: maksut
      TZ: 'Europe/Helsinki'
      PGTZ: 'Europe/Helsinki'
    networks:
      maksut-local-network:
    ports:
      - "15499:5432"
  maksut-mailcatcher-local:
    container_name: "mailcatcher"
    image: "sj26/mailcatcher"
    networks:
      maksut-local-network:
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:1080:1080"
networks:
  maksut-local-network:
  maksut-local-e2e-network:
