<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>maksut</groupId>
  <artifactId>maksut</artifactId>
  <packaging>jar</packaging>
  <version>0.1.0-SNAPSHOT</version>
  <name>maksut</name>
  <description/>
  <scm>
    <url>https://github.com/Opetushallitus/maksut</url>
    <connection>scm:git:git://github.com/Opetushallitus/maksut.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/Opetushallitus/maksut.git</developerConnection>
    <tag>89989dd056f51af794cf3abb8b7a00dfae67bce5</tag>
  </scm>
  <build>
    <sourceDirectory>src/clj</sourceDirectory>
    <testSourceDirectory>test/clj</testSourceDirectory>
    <resources>
      <resource>
        <directory>resources</directory>
      </resource>
    </resources>
    <testResources>
      <testResource>
        <directory>resources</directory>
      </testResource>
    </testResources>
    <directory>target</directory>
    <outputDirectory>target/classes</outputDirectory>
    <plugins/>
  </build>
  <repositories>
    <repository>
      <id>central</id>
      <url>https://repo1.maven.org/maven2/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
    <repository>
      <id>clojars</id>
      <url>https://repo.clojars.org/</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
    <repository>
      <id>github</id>
      <url>https://maven.pkg.github.com/Opetushallitus/packages</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
  </repositories>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>clj-commons</groupId>
        <artifactId>clj-yaml</artifactId>
        <version>1.0.29</version>
      </dependency>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protobuf-java</artifactId>
        <version>3.25.5</version>
      </dependency>
      <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        <version>2.21.0</version>
      </dependency>
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-compress</artifactId>
        <version>1.21</version>
      </dependency>
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-fileupload2-core</artifactId>
        <version>2.0.0-M5</version>
      </dependency>
      <dependency>
        <groupId>org.jsoup</groupId>
        <artifactId>jsoup</artifactId>
        <version>1.23.2</version>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
        <version>2.21.6</version>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>2.21.6</version>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-annotations</artifactId>
        <version>2.21</version>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.dataformat</groupId>
        <artifactId>jackson-dataformat-cbor</artifactId>
        <version>2.21.6</version>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.dataformat</groupId>
        <artifactId>jackson-dataformat-smile</artifactId>
        <version>2.21.6</version>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.datatype</groupId>
        <artifactId>jackson-datatype-jsr310</artifactId>
        <version>2.21.6</version>
      </dependency>
      <dependency>
        <groupId>org.bouncycastle</groupId>
        <artifactId>bcprov-jdk18on</artifactId>
        <version>1.85</version>
      </dependency>
      <dependency>
        <groupId>org.bouncycastle</groupId>
        <artifactId>bcpkix-jdk18on</artifactId>
        <version>1.85</version>
      </dependency>
      <dependency>
        <groupId>org.bouncycastle</groupId>
        <artifactId>bcutil-jdk18on</artifactId>
        <version>1.85</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-buffer</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-common</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-codec</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-codec-base</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-codec-compression</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-codec-dns</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-codec-http</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-codec-http2</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-codec-socks</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-handler</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-handler-proxy</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-resolver</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-resolver-dns</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-transport</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-transport-classes-epoll</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-transport-classes-kqueue</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-transport-native-unix-common</artifactId>
        <version>4.2.17.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-transport-native-epoll</artifactId>
        <version>4.2.17.Final</version>
        <classifier>linux-x86_64</classifier>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-transport-native-epoll</artifactId>
        <version>4.2.17.Final</version>
        <classifier>linux-aarch_64</classifier>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-transport-native-kqueue</artifactId>
        <version>4.2.17.Final</version>
        <classifier>osx-x86_64</classifier>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-server</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-http</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-io</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-util</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-security</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-session</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-xml</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-client</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-alpn-server</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-unixdomain-server</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee9</groupId>
        <artifactId>jetty-ee9-nested</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee9</groupId>
        <artifactId>jetty-ee9-servlet</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee9</groupId>
        <artifactId>jetty-ee9-security</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee9</groupId>
        <artifactId>jetty-ee9-webapp</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee9</groupId>
        <artifactId>jetty-ee9-xml</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee9.websocket</groupId>
        <artifactId>jetty-ee9-websocket-jetty-server</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee9.websocket</groupId>
        <artifactId>jetty-ee9-websocket-jetty-api</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee9.websocket</groupId>
        <artifactId>jetty-ee9-websocket-jetty-common</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.websocket</groupId>
        <artifactId>jetty-websocket-core-common</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.websocket</groupId>
        <artifactId>jetty-websocket-core-server</artifactId>
        <version>12.1.12</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.websocket</groupId>
        <artifactId>jetty-websocket-core-client</artifactId>
        <version>12.1.12</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>clojure</artifactId>
      <version>1.11.4</version>
    </dependency>
    <dependency>
      <groupId>camel-snake-kebab</groupId>
      <artifactId>camel-snake-kebab</artifactId>
      <version>0.4.3</version>
    </dependency>
    <dependency>
      <groupId>cheshire</groupId>
      <artifactId>cheshire</artifactId>
      <version>6.1.0</version>
    </dependency>
    <dependency>
      <groupId>clj-http</groupId>
      <artifactId>clj-http</artifactId>
      <version>3.12.3</version>
    </dependency>
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>s3</artifactId>
      <version>2.33.0</version>
    </dependency>
    <dependency>
      <groupId>com.taoensso</groupId>
      <artifactId>timbre</artifactId>
      <version>6.3.1</version>
    </dependency>
    <dependency>
      <groupId>com.fzakaria</groupId>
      <artifactId>slf4j-timbre</artifactId>
      <version>0.4.1</version>
    </dependency>
    <dependency>
      <groupId>timbre-ns-pattern-level</groupId>
      <artifactId>timbre-ns-pattern-level</artifactId>
      <version>0.1.2</version>
    </dependency>
    <dependency>
      <groupId>com.stuartsierra</groupId>
      <artifactId>component</artifactId>
      <version>1.1.0</version>
    </dependency>
    <dependency>
      <groupId>clj-soup</groupId>
      <artifactId>clojure-soup</artifactId>
      <version>0.1.3</version>
    </dependency>
    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-core</artifactId>
      <version>11.20.1</version>
    </dependency>
    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-database-postgresql</artifactId>
      <version>11.20.1</version>
    </dependency>
    <dependency>
      <groupId>opiskelijavalinnat-utils</groupId>
      <artifactId>java-cas</artifactId>
      <version>2.3.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>buddy</groupId>
      <artifactId>buddy-core</artifactId>
      <version>1.12.0-430</version>
    </dependency>
    <dependency>
      <groupId>fi.vm.sade</groupId>
      <artifactId>auditlogger</artifactId>
      <version>9.2.7-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>fi.vm.sade.java-utils</groupId>
      <artifactId>java-properties</artifactId>
      <version>0.1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>opiskelijavalinnat-utils.viestinvalitys</groupId>
      <artifactId>kirjasto</artifactId>
      <version>1.2.5-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>opiskelijavalinnat-utils</groupId>
      <artifactId>clj-ring-db-cas-session</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>hikari-cp</groupId>
      <artifactId>hikari-cp</artifactId>
      <version>3.0.1</version>
    </dependency>
    <dependency>
      <groupId>metosin</groupId>
      <artifactId>reitit</artifactId>
      <version>0.6.0</version>
    </dependency>
    <dependency>
      <groupId>metosin</groupId>
      <artifactId>schema-tools</artifactId>
      <version>0.13.1</version>
    </dependency>
    <dependency>
      <groupId>metosin</groupId>
      <artifactId>ring-http-response</artifactId>
      <version>0.9.5</version>
    </dependency>
    <dependency>
      <groupId>metosin</groupId>
      <artifactId>ring-swagger-ui</artifactId>
      <version>5.9.0</version>
    </dependency>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>java.jdbc</artifactId>
      <version>0.7.12</version>
    </dependency>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>core.match</artifactId>
      <version>1.1.0</version>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.7.12</version>
    </dependency>
    <dependency>
      <groupId>com.layerware</groupId>
      <artifactId>hugsql</artifactId>
      <version>0.5.3</version>
    </dependency>
    <dependency>
      <groupId>ring</groupId>
      <artifactId>ring</artifactId>
      <version>1.15.5</version>
    </dependency>
    <dependency>
      <groupId>ring</groupId>
      <artifactId>ring-defaults</artifactId>
      <version>0.6.0</version>
    </dependency>
    <dependency>
      <groupId>ring</groupId>
      <artifactId>ring-json</artifactId>
      <version>0.5.1</version>
    </dependency>
    <dependency>
      <groupId>ring</groupId>
      <artifactId>ring-session-timeout</artifactId>
      <version>0.3.0</version>
    </dependency>
    <dependency>
      <groupId>selmer</groupId>
      <artifactId>selmer</artifactId>
      <version>1.12.59</version>
    </dependency>
    <dependency>
      <groupId>prismatic</groupId>
      <artifactId>schema</artifactId>
      <version>1.4.1</version>
    </dependency>
    <dependency>
      <groupId>yogthos</groupId>
      <artifactId>config</artifactId>
      <version>1.2.0</version>
    </dependency>
    <dependency>
      <groupId>environ</groupId>
      <artifactId>environ</artifactId>
      <version>1.2.0</version>
    </dependency>
    <dependency>
      <groupId>org.simplejavamail</groupId>
      <artifactId>simple-java-mail</artifactId>
      <version>8.3.1</version>
    </dependency>
    <dependency>
      <groupId>binaryage</groupId>
      <artifactId>devtools</artifactId>
      <version>1.0.7</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>clj-kondo</groupId>
      <artifactId>clj-kondo</artifactId>
      <version>2024.02.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>reloaded.repl</groupId>
      <artifactId>reloaded.repl</artifactId>
      <version>0.2.4</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>clj-http-fake</groupId>
      <artifactId>clj-http-fake</artifactId>
      <version>1.0.4</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>

<!-- This file was autogenerated by Leiningen.
  Please do not edit it directly; instead edit project.clj and regenerate it.
  It should not be considered canonical data. For more information see
  https://codeberg.org/leiningen/leiningen -->
