name: setup-next-env
description: 'Setup Next.js environment'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: src/maksut-ui/package-lock.json
    - uses: actions/cache@v4
      id: node_modules-cache
      with:
        path: ${{ github.workspace }}/src/maksut-ui/node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('./src/maksut-ui/package-lock.json') }}
    - name: Cache Next.js
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/src/maksut-ui/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('./src/maksut-ui/package-lock.json') }}-${{ hashFiles('./src/maksut-ui/next.config.*', './src/**/*.ts', './src/**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('./src/maksut-ui/package-lock.json') }}-
    - name: Install npm dependencies
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd src/maksut-ui
        npm ci --include=dev