name: Maksut-ui deploy
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        description: Commit hash if you want to deploy a specific version
      environment:
        type: choice
        description: Environment where to deploy
        options:
          - untuva
          - hahtuva
          - pallero
          - sade
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}
          fetch-depth: '0'
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Set up Next env
        uses: ./.github/actions/setup-next-env
      - name: Install NPM dependencies
        run: |
          cd cdk
          npm ci
          npm install -g aws-cdk
      - name: Configure AWS credentials for DEV
        if: ${{ inputs.environment == 'hahtuva' || inputs.environment == 'untuva' || inputs.environment == 'pallero' }}
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ secrets.AWS_OPINTOPOLKU_DEV_ROLE_ARN }}
          role-session-name: maksut-ui-deploy
          aws-region: eu-west-1
      - name: Configure AWS credentials for PROD
        if: ${{ inputs.environment == 'sade' }}
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ secrets.AWS_OPINTOPOLKU_PROD_ROLE_ARN }}
          role-session-name: maksut-ui-deploy
          aws-region: eu-west-1
      - name: Deploy Next.js app
        run: |
          cd cdk
          cdk deploy SovellusStack --require-approval never -c "environment=${{ inputs.environment }}"